### ISSUE TITLE
on page load, getting Class does not exist error

### ISSUE THREAD

**Issue by allabakash** [ShiniWolf/angular2-symfony3#4]
`Class AppBundle\Controller\int does not exist in AppBundle\Controller\UsersController (which is being imported from "/var/www/html/angular2-symfony2/app/config/routing.yml").
`

do you have clue?

**Comment by ShiniWolf** [comment]
You need to switch to PHP 7 for types Int

The User controller is an example, you can update getAction function and remove type int for $id parameter
